### ISSUE TITLE
Port your resume to resume.json

### ISSUE THREAD

**Issue by aloisdg** [seckin206/resume#3]
Hello,

Just a quick issue to give you a link to [JSONResume](http://jsonresume.org/). JSONResume is a JSON-based standard for resumes. You may want to port your resume to this spec.

Also, if you are looking to manipulate your resume with .NET, I coded a nuget package for it : [SharpResume](https://github.com/aloisdg/SharpResume).

Cheers,

**Comment by seckin206** [comment]
Thanks, I'll have a look.
